---
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${{ secrets.monitoring_puid }}
      - PGID=${{ secrets.monitoring_pgid }}
      - TZ=America/Chicago
    volumes:
      - tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=${{ secrets.monitoring_puid }}
      - PGID=${{ secrets.monitoring_pgid }}
    ports:
      - 3000:3000
    volumes:
      - homepage:/app/config # Make sure your local config directory exists
    restart: unless-stopped

volumes:
  tautulli:
    external: true
  uptime-kuma:
    external: true
  homepage:
    external: true
...
