### CHANGE ALL PGID AND PUID INSTANCES TO YOURS OR YOUR VOLUMES MAY NOT (PROBABLY WON'T) WORK ###
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000 #change to your service account's
      - PGID=1000 #change to your service account's
      - TZ=America/Chicago
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - plex:/config
      - tv-shows:/tv
      - cartoons:/cartoons
      - anime:/anime
      - movies:/movies
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000 #change to your service account's
      - PGID=1000 #change to your service account's
      - TZ=America/Chicago
    volumes:
      - sonarr:/config
      - cartoons:/tv/cartoons
      - tv-shows:/tv/shows
      - anime:/tv/anime
      - complete_downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000 #change to your service account's
      - PGID=1000 #change to your service account's
      - TZ=America/Chicago
    volumes:
      - radarr:/config
      - movies:/movies
      - complete_downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=America/Chicago
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000 #change to your service account's
      - PGID=1000 #change to your service account's
      - TZ=America/Chicago
    volumes:
      - bazarr:/config
      - cartoons:/tv/cartoons
      - tv-shows:/tv/shows
      - anime:/tv/anime
      - movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000 #change to your service account's
      - PGID=1000  #change to your service account's
      - TZ=America/Chicago
    volumes:
      - overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000 
      - TZ=America/Chicago
    volumes:
      - heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  plex:
    external: true
  sonarr:
    external: true
  radarr:
    external: true
  prowlarr:
    external: true
  bazarr:
    external: true
  overseerr:
    external: true
  tv-shows:
    external: true
  cartoons:
    external: true
  anime:
    external: true
  movies:
    external: true
  complete_downloads:
    external: true
  heimdall:
    external: true