services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/Chicago
      - VERSION=docker
      - PLEX_CLAIM=claim-xSUmNztyb7yrwhJDhngc
    volumes:
      - /plex:/config
      - /tv-shows:/tv
      - /cartoons:/cartoons
      - /anime:/anime
      - /movies:/movies
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /sonarr:/config
      - /cartoons:/tv/cartoons
      - /tv-shows:/tv/shows
      - /anime:/tv/anime
      - /completed_downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /radarr:/config
      - /movies:/movies
      - /completed_downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=America/Chicago
    volumes:
      - /prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    #PGID and PUID are both 1000 by default, change if you have service accounts your containers use to access your media
    #Volume mount points may need to be changed if you use NFS mounts instead of local storage
    #Plex claim and timezone information will need to be modified to your specific instance