---
services:
  actual:
    image: actualbudget/actual-server:latest
    container_name: actual
    ports:
      - 5006:5006
    volumes:
      - actual:/data # Make sure your local config directory exists
    restart: unless-stopped

volumes:
  actual:
    external: true
...
