---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID= $PUID
      - PGID= $PGID
      - TZ=America/Chicago
      - VERSION=docker
      #- PLEX_CLAIM= $PLEX_CLAIM #optional, add the claim token here if you have it
    env_file: plexstack.env
    volumes:
      - ./config/plex:/config
      - shows:/tv
      - cartoons:/cartoons
      - anime:/anime
      - movies:/movies
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID= $PUID
      - PGID= $PGID
      - TZ=America/Chicago
    env_file: plexstack.env
    volumes:
      - ./config/sonarr:/config
      - cartoons:/tv/cartoons #clean up container paths. Shouldn't need /tv/shows, just make it /shows, /cartoons /anime. Do this for Bazarr too
      - shows:/tv/shows
      - anime:/tv/anime
      - complete_downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID= $PUID
      - PGID= $PGID
      - TZ=America/Chicago
    env_file: plexstack.env
    volumes:
      - ./config/radarr:/config
      - movies:/movies
      - complete_downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=America/Chicago
    env_file: plexstack.env
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID= $PUID
      - PGID= $PGID
      - TZ=America/Chicago
    env_file: plexstack.env
    volumes:
      - ./config/bazarr:/config
      - cartoons:/tv/cartoons
      - shows:/tv/shows
      - anime:/tv/anime
      - movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID= $PUID
      - PGID= $PGID
      - TZ=America/Chicago
    env_file: plexstack.env
    volumes:
      - ./config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

volumes:
  shows:
    external: true
  cartoons:
    external: true
  anime:
    external: true
  movies:
    external: true
  complete_downloads:
    external: true
...
