services:
  server:
    image: docker.gitea.com/gitea:latest-rootless
    container_name: gitea-server
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - GITEA__database__DB_TYPE=postgres
      - 'GITEA__database__HOST=${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}'
      - 'GITEA__database__NAME=${POSTGRES_DB:?POSTGRES_DB not set}'
      - 'GITEA__database__USER=${POSTGRES_USER:?POSTGRES_USER not set}'
      - 'GITEA__database__PASSWD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}'
      - GITEA__server__SSH_PORT=2222
      - 'GITEA__server__ROOT_URL=$ROOT_URL'
    env_file: .env
    restart: unless-stopped
    volumes:
      - /cert/file/location:/var/lib/gitea/custom/certificate.crt
      - /key/file/location:/var/lib/gitea/custom/certificate.key
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "443:3000" #change ports as needed
      - "80:3080"
      - "2222:2222" #not this one, needed for db to communicate
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    container_name: gitea-db
    restart: unless-stopped
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER not set}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}'
      - 'POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB not set}'
    env_file: .env
    volumes:
      - gitea-db:/var/lib/postgresql/data

volumes:
  gitea-data:
    driver: local
  gitea-config:
    driver: local
  gitea-db:
    driver: local
