---
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID= $PUID
      - PGID= $PGID
      - TZ=America/Chicago
    env_file: monitoringstack.yaml
    volumes:
      - ./config/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    env_file: monitoringstack.yaml
    volumes:
      - ./config/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always
...
