services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: $PUID
      PGID: $PGID
    ports:
      - 3000:3000
    env_file: homepage.env
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    restart: unless-stopped
...
