- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank

- openweathermap:
    label: Overland Park #optional
    latitude: "{{HOMEPAGE_VAR_OPENWEATHER_LATITUDE}}"
    longitude: "{{HOMEPAGE_VAR_OPENWEATHER_LONGITUDE}}"
    units: metric # metric or imperial
    provider: openweathermap
    apiKey: "{{HOMEPAGE_VAR_OPENWEATHER_KEY}}" # required only if not using provider, this reveals api key in requests
    cache: 5 # Time in minutes to cache API responses, to stay within limits

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
      hour12: true
